import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#00658f",
        "primary-container": "#00a6e8",
        "on-primary": "#ffffff",
        "on-primary-container": "#003751",
        "primary-fixed": "#c7e7ff",
        "primary-fixed-dim": "#86cfff",
        "on-primary-fixed": "#001e2e",
        "on-primary-fixed-variant": "#004c6d",
        "inverse-primary": "#86cfff",

        "secondary": "#515f73",
        "secondary-container": "#d2e1f8",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#566478",
        "secondary-fixed": "#d5e3fb",
        "secondary-fixed-dim": "#b9c7df",
        "on-secondary-fixed": "#0e1c2d",
        "on-secondary-fixed-variant": "#3a485b",

        "tertiary": "#5a5f61",
        "tertiary-container": "#989d9f",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#303536",
        "tertiary-fixed": "#dfe3e5",
        "tertiary-fixed-dim": "#c3c7c9",
        "on-tertiary-fixed": "#171c1e",
        "on-tertiary-fixed-variant": "#434849",

        "surface": "#f6faff",
        "surface-pure": "#FFFFFF",
        "surface-bright": "#f6faff",
        "surface-dim": "#c9dcee",
        "surface-variant": "#d2e5f6",
        "surface-tint": "#00658f",
        "surface-container": "#e0f0ff",
        "surface-container-low": "#ebf5ff",
        "surface-container-high": "#d8ebfc",
        "surface-container-highest": "#d2e5f6",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#0a1d2a",
        "on-surface-variant": "#3e4850",

        "background": "#f6faff",
        "background-alt": "#F8FAFC",
        "on-background": "#0a1d2a",

        "border-subtle": "#DCECF2",
        "outline": "#6e7881",
        "outline-variant": "#bdc8d1",

        "inverse-surface": "#21323f",
        "inverse-on-surface": "#e6f2ff",

        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",

        wenture: {
          blue: "#00A6E8",
          blueHover: "#0093CE",
          blueDark: "#00658F",
          navy: "#0A192A",
          surface: "#F6FAFF",
          border: "#DCECF2",
          muted: "#5F7180",
        },
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "80px",
        "margin-mobile": "20px",
        "section-gap": "120px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "container-max": "1280px",
        gutter: "24px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        heading: ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-xl": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "button-text": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "button-text": ["16px", { lineHeight: "20px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
      boxShadow: {
        ambient: "0px 4px 20px rgba(10, 25, 42, 0.04)",
        "card-hover": "0px 8px 30px rgba(10, 25, 42, 0.08)",
        glow: "0 0 25px rgba(0, 166, 232, 0.35)",
        "glow-lg": "0 0 50px rgba(0, 166, 232, 0.25)",
      },
    },
  },
  plugins: [],
};

export default config;
