export interface FeaturedItem {
  id: string;
  name: string;
  category: "Featured Business" | "Featured Startup" | "Featured Franchise" | "Featured Dealership" | "Featured EXIM";
  type: string;
  sector: string;
  location: string;
  investmentRange: string;
  shortDescription: string;
  opportunityType: string;
  slug?: string;
  imageUrl: string;
  tag?: string;
}

export const FEATURED_DATA: Record<string, FeaturedItem[]> = {
  businesses: [
    {
      id: "feat-biz-1",
      name: "Apex Precision Tooling Works",
      category: "Featured Business",
      type: "Established Manufacturing",
      sector: "Manufacturing",
      location: "Pune, Maharashtra",
      investmentRange: "₹50L – ₹1Cr",
      shortDescription: "Profitable CNC precision components manufacturer seeking strategic expansion capital for an automated line.",
      opportunityType: "Equity / Partnership",
      slug: "apex-precision-tooling",
      imageUrl: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
      tag: "12+ Years Operation",
    },
    {
      id: "feat-biz-2",
      name: "GreenEarth Packaging Solutions",
      category: "Featured Business",
      type: "Eco-Packaging Unit",
      sector: "Manufacturing",
      location: "Ahmedabad, Gujarat",
      investmentRange: "₹25L – ₹50L",
      shortDescription: "Biodegradable paper & bagasse container manufacturing unit with existing B2B retail supply contracts.",
      opportunityType: "Business Expansion",
      slug: "greenearth-packaging",
      imageUrl: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80",
      tag: "B2B Supply Contracts",
    },
    {
      id: "feat-biz-3",
      name: "MedVantage Diagnostic Network",
      category: "Featured Business",
      type: "Healthcare Services",
      sector: "Healthcare",
      location: "Hyderabad, Telangana",
      investmentRange: "₹50L – ₹1Cr",
      shortDescription: "Modern pathology and radiology center cluster looking for capital to open 4 new neighborhood diagnostic hubs.",
      opportunityType: "Expansion Capital",
      slug: "medvantage-diagnostic",
      imageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80",
      tag: "High Footfall Hubs",
    },
  ],
  startups: [
    {
      id: "feat-start-1",
      name: "VoltGrid Mobility",
      category: "Featured Startup",
      type: "EV Infrastructure",
      sector: "EV & Mobility",
      location: "Bengaluru, Karnataka",
      investmentRange: "₹25L – ₹50L",
      shortDescription: "Smart EV charging station management and battery swap IoT network for commercial three-wheeler fleets.",
      opportunityType: "Early-Stage Investment",
      slug: "voltgrid-mobility",
      imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80",
      tag: "IoT Enabled",
    },
    {
      id: "feat-start-2",
      name: "CloudDine Tech",
      category: "Featured Startup",
      type: "FoodTech & Cloud POS",
      sector: "Technology",
      location: "Gurugram, Haryana",
      investmentRange: "₹10L – ₹25L",
      shortDescription: "All-in-one kitchen automation and inventory prediction SaaS built specifically for multi-brand cloud kitchens.",
      opportunityType: "Seed Investment",
      slug: "clouddine-tech",
      imageUrl: "https://images.unsplash.com/photo-1556742049-0a67e55722c0?auto=format&fit=crop&w=800&q=80",
      tag: "Growing SaaS",
    },
    {
      id: "feat-start-3",
      name: "KrishiBridge Agritech",
      category: "Featured Startup",
      type: "Agro Supply Chain",
      sector: "Agriculture",
      location: "Nashik, Maharashtra",
      investmentRange: "₹25L – ₹50L",
      shortDescription: "Farm-to-fork direct procurement digital platform connecting certified horticulture farmers to urban grocers.",
      opportunityType: "Startup Capital",
      slug: "krishibridge-agritech",
      imageUrl: "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=800&q=80",
      tag: "Direct Farm Procurement",
    },
  ],
  franchises: [
    {
      id: "feat-fran-1",
      name: "Urban Brew Specialty Coffee",
      category: "Featured Franchise",
      type: "Artisanal Cafe Franchise",
      sector: "Food & Beverage",
      location: "Pan-India Expansion",
      investmentRange: "₹25L – ₹50L",
      shortDescription: "Rapidly growing specialty cafe chain offering master and unit franchise formats with complete store setup support.",
      opportunityType: "Franchise Opportunity",
      slug: "urban-brew-specialty-cafe",
      imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
      tag: "18+ Live Outlets",
    },
    {
      id: "feat-fran-2",
      name: "LittleSprouts Pre-Schools",
      category: "Featured Franchise",
      type: "Early Childhood Education",
      sector: "Education",
      location: "Tier-2 & Tier-3 Cities",
      investmentRange: "₹10L – ₹25L",
      shortDescription: "Award-winning early childhood learning curriculum with turnkey branding, teacher training, and admissions marketing.",
      opportunityType: "Franchise Opportunity",
      slug: "littlesprouts-preschools",
      imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80",
      tag: "Turnkey Setup",
    },
    {
      id: "feat-fran-3",
      name: "FitPulse Gyms & Wellness",
      category: "Featured Franchise",
      type: "Fitness & Wellness",
      sector: "Healthcare",
      location: "Metro & Tier-1 Hubs",
      investmentRange: "₹50L – ₹1Cr",
      shortDescription: "Boutique high-density fitness studio franchise with automated access, imported equipment, and mobile app booking.",
      opportunityType: "Franchise Opportunity",
      slug: "fitpulse-gyms",
      imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80",
      tag: "High Member Retention",
    },
  ],
  dealerships: [
    {
      id: "feat-deal-1",
      name: "ElectraVolt EV Two-Wheeler Dealership",
      category: "Featured Dealership",
      type: "Authorized Dealership & Service",
      sector: "EV & Mobility",
      location: "State-wide Territory Rights",
      investmentRange: "₹10L – ₹25L",
      shortDescription: "Authorized commercial dealership for high-speed electric scooters with showroom design support and spares backup.",
      opportunityType: "Dealership License",
      slug: "electravolt-dealership",
      imageUrl: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80",
      tag: "Territory Exclusivity",
    },
    {
      id: "feat-deal-2",
      name: "AquaPure Commercial Filtration",
      category: "Featured Dealership",
      type: "Industrial Dealership",
      sector: "Business Services",
      location: "District Level Distribution",
      investmentRange: "₹5L – ₹10L",
      shortDescription: "Regional distributorship for commercial reverse osmosis and UV water treatment plants for offices, hospitals, and factories.",
      opportunityType: "Authorized Distributorship",
      slug: "aquapure-filtration",
      imageUrl: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80",
      tag: "High B2B Margins",
    },
    {
      id: "feat-deal-3",
      name: "Solaris Power Solutions",
      category: "Featured Dealership",
      type: "Rooftop Solar Dealership",
      sector: "CleanTech",
      location: "Tier-1 & Tier-2 Clusters",
      investmentRange: "₹10L – ₹25L",
      shortDescription: "Authorized channel partner program for tier-1 residential and commercial rooftop solar installation systems.",
      opportunityType: "Channel Dealership",
      slug: "solaris-power-dealership",
      imageUrl: "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80",
      tag: "Govt Subsidy Supported",
    },
  ],
  exim: [
    {
      id: "feat-exim-1",
      name: "IndoSpice Global Exports",
      category: "Featured EXIM",
      type: "Agro Commodity Export",
      sector: "EXIM",
      location: "Kochi, Kerala (Global Hubs)",
      investmentRange: "₹50L – ₹1Cr",
      shortDescription: "Certified organic spices, cardamom, and black pepper processing export partnership for European & GCC buyers.",
      opportunityType: "EXIM Partnership",
      slug: "indospice-global-exports",
      imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80",
      tag: "Confirmed Global Orders",
    },
    {
      id: "feat-exim-2",
      name: "Vedic Silk & Handloom Exporters",
      category: "Featured EXIM",
      type: "Textile & Apparel Export",
      sector: "Fashion",
      location: "Surat, Gujarat",
      investmentRange: "₹25L – ₹50L",
      shortDescription: "Premium artisan silk fabric and ready-to-wear ethnic wear export house supplying North American retail boutiques.",
      opportunityType: "Export Consortium",
      slug: "vedic-silk-handlooms",
      imageUrl: "https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?auto=format&fit=crop&w=800&q=80",
      tag: "Export Quality Certified",
    },
    {
      id: "feat-exim-3",
      name: "AuraStone Granites & Ceramics",
      category: "Featured EXIM",
      type: "Building Materials Export",
      sector: "Real Estate",
      location: "Jaipur, Rajasthan",
      investmentRange: "₹50L – ₹1Cr",
      shortDescription: "Polished natural marble, quartz, and architectural granite processing unit supplying Middle East infrastructure projects.",
      opportunityType: "International Trade",
      slug: "aurastone-granites",
      imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
      tag: "Direct Quarry Access",
    },
  ],
};
